/**
 * Single Responsibility: Rigorously validates the generated product item against constraints, formatting rules, and tier leakage.
 * Expected to be called from: src/generate.js
 */
const FORBIDDEN_TIER_WORDS = ['premium', 'mid-premium', 'value tier'];
const BARE_IMPERATIVE_RE = /^(wipe|do not|don't|clean|dry|avoid|use|apply|dust|store|keep|remove|scrub)\b/i;
const RAW_DIMENSION_RE = /\b\d+(?:\.\d+)?\s*(?:m|cm|mm|in|inch|inches|ft|feet)\b\s*(?:[lwhd]\b)?(?:\s*x\s*\d+(?:\.\d+)?\s*(?:m|cm|mm|in|inch|inches|ft|feet)\b\s*(?:[lwhd]\b)?)+/i;

function normalize(v) {
  return String(v).trim().toLowerCase();
}

function includesNormalized(text, value) {
  return normalize(text).includes(normalize(value));
}

function validateItem(item, sourceProduct, options = {}) {
  const errors = [];

  const requiredTopLevel = ['description', 'specifications', 'care_and_maintenance', 'warranty', 'returns', 'quality_promise'];
  for (const key of requiredTopLevel) {
    if (!(key in item) || item[key] === undefined || item[key] === null) {
      errors.push(`Missing top-level field: ${key}`);
    }
  }

  if (item.description) {
    if (!item.description.summary) errors.push('Missing description.summary');
    // Summary should be exactly 4-6 sentences, unless relaxLengthCheck is true
    const summary = item.description.summary || '';
    if (!options.relaxLengthCheck) {
      const sentenceCount = (summary.match(/[.!?]/g) || []).length;
      if (sentenceCount < 4 || sentenceCount > 6) {
        errors.push(`description.summary should be between 4 and 6 sentences; found ${sentenceCount}`);
      }
      const wordCount = summary.trim().split(/\s+/).filter(Boolean).length;
      if (wordCount < 70 || wordCount > 110) {
        errors.push(`description.summary should be ~70-110 words; found ${wordCount}`);
      }
    }
    
    if (RAW_DIMENSION_RE.test(summary)) {
      errors.push('description.summary must not include raw dimension strings');
    }

    if (sourceProduct && sourceProduct.product_short_name) {
      const shortName = sourceProduct.product_short_name;
      const escapedShortName = shortName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const regex = new RegExp(`\\b${escapedShortName}\\b`, 'gi');
      const matches = summary.match(regex) || [];
      if (matches.length !== 1) {
        errors.push(`description.summary must mention product_short_name exactly once; found ${matches.length}`);
      } else {
        const sentences = summary.match(/[^.!?]+[.!?]+/g)?.map(s => s.trim()).filter(Boolean) || (summary.trim() ? [summary.trim()] : []);
        const closingSentence = sentences.length > 0 ? sentences[sentences.length - 1] : '';
        const closingRegex = new RegExp(`\\b${escapedShortName}\\b`, 'i');
        if (!closingRegex.test(closingSentence)) {
          errors.push(`description.summary must mention product_short_name in the CLOSING sentence specifically — found it in an earlier sentence instead.`);
        }
      }
    }
    
    if (item.description.key_features && Array.isArray(item.description.key_features)) {
      for (const bullet of item.description.key_features) {
        if (!bullet || typeof bullet !== 'string') {
          errors.push('description.key_features must contain only strings');
        }
      }
    } else {
      errors.push('Missing description.key_features array');
    }


  }

  // Specifications are NOT generated by the LLM; they are copied from source.
  // Validate that: 1) all values present match source exactly, 2) no extra
  // fields are added, 3) all non-empty source fields are present in output.
  if (item.specifications && sourceProduct) {
    const allowedSpecFields = ['dimensions', 'primary_material', 'secondary_material', 'weight', 'assembly_required', 'seating_capacity', 'color_finish'];
    // Check that all fields in item.specifications are allowed and match source.
    for (const field in item.specifications) {
      const generated = item.specifications[field];
      const source = sourceProduct[field];
      if (!allowedSpecFields.includes(field)) {
        errors.push(`specifications.${field} should not be generated; it is a source-copy-only field`);
      } else if (source === undefined || source === null || source === '') {
        errors.push(`specifications.${field} should not be present if missing in source`);
      } else if (normalize(generated) !== normalize(source)) {
        errors.push(`specifications.${field} does not match source data exactly`);
      }
    }
    // Check that all non-empty source fields are present in generated item.
    for (const field of allowedSpecFields) {
      if (sourceProduct[field] !== undefined && sourceProduct[field] !== null && sourceProduct[field] !== '') {
        if (!(field in item.specifications)) {
          errors.push(`specifications.${field} is present in source but missing in output`);
        }
      }
    }
  }

  // Field count checks
  if (item.care_and_maintenance) {
    const instructions = item.care_and_maintenance.instructions;
    const avoid = item.care_and_maintenance.avoid;
    if (!Array.isArray(instructions) || instructions.length !== 3) {
      errors.push('care_and_maintenance.instructions must have exactly 3 items');
    }
    if (!Array.isArray(avoid) || avoid.length !== 2) {
      errors.push('care_and_maintenance.avoid must have exactly 2 items');
    }
    for (const line of [...(instructions || []), ...(avoid || [])]) {
      if (typeof line === 'string' && BARE_IMPERATIVE_RE.test(line.trim())) {
        errors.push(`Polite-tone flag (bare imperative, human review can override): "${line}"`);
      }
    }
  } else {
    errors.push('Missing care_and_maintenance');
  }

  if (item.warranty) {
    const points = Array.isArray(item.warranty.points) ? item.warranty.points : [];
    if (points.length > 4) {
      errors.push('warranty.points must have at most 4 items');
    }
    if (!item.warranty.status_line || !/^\*\*(Yes|No)\*\*, it has a warranty of \*\*\d+\s+months\*\*\.$/.test(item.warranty.status_line.trim())) {
      errors.push('warranty.status_line must be exactly: "**Yes**, it has a warranty of **N months**." or "**No**, it has a warranty of **0 months**."');
    }
    if (points.length > 0 && points.some((point) => typeof point !== 'string' || !point.trim())) {
      errors.push('warranty.points must contain only non-empty strings');
    }
  } else {
    errors.push('Missing warranty');
  }

  if (item.returns) {
    if (!Array.isArray(item.returns.condition) || item.returns.condition.length !== 3) {
      errors.push('returns.condition must have exactly 3 items');
    }
  } else {
    errors.push('Missing returns');
  }

  // Tier leakage check — description must never reveal the internal price tier.
  const descriptionText = item.description ? JSON.stringify(item.description).toLowerCase() : '';
  for (const word of FORBIDDEN_TIER_WORDS) {
    if (descriptionText.includes(word)) {
      errors.push(`Tier leakage: description contains forbidden word "${word}"`);
    }
  }
  if (/[₹$]\s?\d/.test(descriptionText) || /\bprice\b/i.test(descriptionText)) {
    errors.push('Tier leakage: description appears to reference a price figure');
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

module.exports = { validateItem };
